sonar.projectKey=food-ordering-payment-service
sonar.projectName=Payment Service - Food Ordering System
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
